log parser: change formatting (#52269)
* drop line wrapping in the log parser
* use a `grep` / `diff` style format
* fix bug where warning in error context is rendered red instead of yellow
* drop extra trailing newline in `spack log-parse`

Fixed line wrapping is problematic:

* cannot select and copy the full line by triple clicking
* error messages with "underline" on the next line are confusing with line wrapping:
  ```
  error: this is a long line
         ^^^^

  error: this is a lo
  ng line
         ^^^^
  ```

With this commit, the style is like this:

```
-- lines x to y --
  pre context a
  pre context b
> error: the error line
  post context a
  post context b
```